const movies = [
  // =====================
  // NOW SHOWING (25)
  // =====================

  {
    id: 1,
    title: "Elemental",
    genre: "Animation",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
  },
  {
    id: 2,
    title: "Kung Fu Panda 4",
    genre: "Animation",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
  },
  {
    id: 3,
    title: "Dune: Part Two",
    genre: "Action",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
  },
  {
    id: 4,
    title: "Godzilla x Kong: The New Empire",
    genre: "Action",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
  },
  {
    id: 5,
    title: "The Fall Guy",
    genre: "Action",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/e7olqFmzcIX5c23kX4zSmLPJi8c.jpg",
  },
  {
    id: 6,
    title: "Civil War",
    genre: "Drama",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
  },
  {
    id: 7,
    title: "Furiosa: A Mad Max Saga",
    genre: "Action",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
  },
  {
    id: 8,
    title: "Kingdom of the Planet of the Apes",
    genre: "Sci-Fi",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
  },
  {
    id: 9,
    title: "Deadpool & Wolverine",
    genre: "Action",
    year: 2024,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
  },
  {
    id: 10,
    title: "Wonka",
    genre: "Fantasy",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
  },
  {
    id: 11,
    title: "Migration",
    genre: "Animation",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
  },
  {
    id: 12,
    title: "Wish",
    genre: "Animation",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
  },
  {
    id: 13,
    title: "Aquaman and the Lost Kingdom",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
  },
  {
    id: 14,
    title: "The Marvels",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/Ag3D9qXjhJ2FUkrlJ0Cv1pgxqYQ.jpg",
  },
  {
    id: 15,
    title: "Oppenheimer",
    genre: "Drama",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
  },
  {
    id: 16,
    title: "Barbie",
    genre: "Comedy",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
  },
  {
    id: 17,
    title: "Fast X",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
  },
  {
    id: 18,
    title: "Transformers: Rise of the Beasts",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
  },
  {
    id: 19,
    title: "Spider-Man: Across the Spider-Verse",
    genre: "Animation",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
  },
  {
    id: 20,
    title: "Elemental",
    genre: "Animation",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
  },
  {
    id: 21,
    title: "The Little Mermaid",
    genre: "Fantasy",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
  },
  {
    id: 22,
    title: "Gran Turismo",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
  },
  {
    id: 23,
    title: "Blue Beetle",
    genre: "Action",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
  },
  {
    id: 24,
    title: "Trolls Band Together",
    genre: "Animation",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
  },
  {
    id: 25,
    title: "Napoleon",
    genre: "Drama",
    year: 2023,
    status: "NOW",
    poster: "https://image.tmdb.org/t/p/w500/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg",
  },

  // =====================
  // UPCOMING (2)
  // =====================

  {
    id: 26,
    title: "Joker: Folie à Deux",
    genre: "Drama",
    year: 2024,
    status: "UPCOMING",
    poster: "https://image.tmdb.org/t/p/w500/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
  },
  {
    id: 27,
    title: "Gladiator II",
    genre: "Action",
    year: 2024,
    status: "UPCOMING",
    poster: "https://image.tmdb.org/t/p/w500/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg",
  },
];

export default movies;
